### ISSUE TITLE
Doesn't clean up submodule archives

### ISSUE THREAD

**Issue by bibby** [meitar/git-archive-all.sh#23]
Script cleans up after the outermost archive, but the archive for the submodule(s) linger.
This prevents back-to-back executions without manual intervention.

Ammendment: This appears to be important, my format is `tar.gz`.  I see now that `tar` and `zip` are cleaned up.

**Comment by bibby** [comment]
compressed archives can't be concatenated. Not sure what I was thinking. Sorry!

**Comment by meitar** [comment]
:) No worries.
